application: rolfm2-1013
version: 2
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /app/
  static_dir: app/

- url: .*
  script: main.php

- url: /(.+)
  script: main.php
